#pragma once

enum class Lex
{
    NONE,
    NAME,
    NUMBER,
    DOUBLE,
    FLOAT,
    DECIMAL,
    STRINGLITERAL,
    CHARLITERAL,
    PREPROC_DIRECTIVE,

    ABSTRACT, AS, BASE, BOOL, BREAK, BYTE,
    CASE, CATCH, CHAR, CHECKED, CLASS, CONST,
    CONTINUE, DEFAULT, DELEGATE, DO,
    ELSE, ENUM, EVENT, EXPLICIT, EXTERN, FALSE,
    FINALLY, FIXED, FOR, FOREACH, GOTO,
    IF, IMPLICIT, IN, INT, INTERFACE, INTERNAL,
    IS, LOCK, LONG, NAMESPACE, NEW, NULL_,
    OBJECT, OPERATOR, OUT, OVERRIDE, PARAMS, PRIVATE,
    PROTECTED, PUBLIC, READONLY, REF, RETURN, SBYTE,
    SEALED, SHORT, SIZEOF, STACKALLOC, STATIC, STRING,
    STRUCT, SWITCH, THIS, THROW, TRUE, TRY, VAR,
    TYPEOF, UINT, ULONG, UNCHECKED, UNSAFE, USHORT,
    USING, VIRTUAL, VOID, VOLATILE, WHILE,


    PLUS, MINUS, MULT, DIV, MOD,
    PLUS_ASSIGN, MINUS_ASSIGN, MULT_ASSIGN, DIV_ASSIGN, MOD_ASSIGN,
    BITWISE_NOT, BITWISE_XOR, XOR_ASSIGN, AND_ASSIGN, OR_ASSIGN,
    LSHIFT, RSHIFT, LSHIFT_ASSIGN,RSHIFT_ASSIGN,
    ASSIGN, EQ, NE, LT, LE, GT, GE,
    AND, OR, NOT, BITWISE_AND, BITWISE_OR,
    INCREMENT, DECREMENT,
    DOT, COMMA, COLON, SEMICOLON,
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,
    ARROW, QUESTION, NULL_COALESCING, NULL_CONDITIONAL,
    NULL_COALESCING_ASSIGN, INTERPOLATED_STRING, VERBATIM_STRING,
    EOT
};